/* ScriptService.idl -- Script Execution service for Web CorbaScript

Copyright (C) 1999-2000 Minoru Development Corporation.

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

Alternatively, you can redistribute it and/or modify it under the terms
of the CorbaScript distribution.  These terms are described in the file
wcs/CorbaScript-1.3.1+/COPYRIGHT in this package.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.

Contact:  Brian Bray
	  http://www.minoru-development.com
          mailto:brianbr@openhealth.com

*/

#ifndef _SCRIPTSERVICE_IDL_
#define _SCRIPTSERVICE_IDL_

#include <orb.idl>

module Scripting
{

	struct result 
	{
		string output;            // print/prinln output
		string eval_result;         // _toString() of eval() result
	};

	typedef sequence< result > ResultSeq;
	typedef string Script;
	typedef sequence< Script > ScriptSeq;

	exception ScriptError { long which; string message; };

	interface ScriptServer {
		ResultSeq eval_seq(in ScriptSeq scripts)
			raises( ScriptError );
	};

};


#endif //_SCRIPTSERVICE_IDL_

