
#define A 1.23456789012345D

const fixed B = 3.45789012345678901D;

const fixed C = A * B;

const fixed D = 1000D;

const wchar wc1 = L'c';
const wchar wc2 = 'c';

const wstring ws = L"abcd";

module TimeBase {

	typedef unsigned long long TimeT;

};

const TimeBase::TimeT MICROSECOND = 10;
const TimeBase::TimeT MILLISECOND = MICROSECOND * 1000;
const TimeBase::TimeT SECOND = MILLISECOND * 1000;
const TimeBase::TimeT MINUTE = SECOND * 60;
const TimeBase::TimeT HOUR = MINUTE * 60;
const TimeBase::TimeT DAY = HOUR * 24;

